:wrench: Updates isntallation

diff --git a/.vscode/install-extentions b/.vscode/install-extentions
--- a/.vscode/install-extentions
+++ b/.vscode/install-extentions
@@ -1,6 +1,31 @@
 #!/usr/bin/env zsh 
 
+DIR=$(pwd)
 
-exho "Installing VS code extentions from 'vscode-extentions.txt'..."
-cat .vscode-extentions.txt | xargs -L 1 code --install-extentions
-echo "Extentions installed successfully."
+echo "Installing VS code extentions from 'vscode-extentions.txt'..."
+
+echo $DIR
+
+if [ "$1" == "export" ]; then
+	if [ -f .vscode-extensions.txt ]; then		
+		read -p ".vscode-extentions.txt already exists. Do you want to overwrite? (y/n): " confirm
+
+		if [ "$confirm" != "y" ]; then
+			echo "Export canceled."
+			exit 0
+		fi
+	fi
+	
+	code --list-extentions > .vscode-extentions.txt
+	echo "Extentions exported to .vscode-extentions.txt"
+elif [ "$1" == "install" ]; then
+	if [ ! -f .vscode-extentions.txt ]; then
+		echo ".vscode-extentions.txt not found. Please make sure that extentions are exported into a file before installing"
+		exit 1
+	fi
+	
+	cat .vscode-extentions.txt | xargs -L 1 code --install-extentions
+	echo "Extentions installed successfully."
+else
+	echo "Usage: $0 {export|instsall}"
+fi
